language: node_js
node_js:
  - "0.12"
  - "iojs"
services:
  - mysql
sudo: required
before_script:
  - mysql -e 'create database test_orm;'
  - mysql -e 'create table test(id int not null, name varchar(32) not null);'
after_success:
  - ./node_modules/.bin/mocha --require babel/register
