language: node_js
node_js:
  - "0.12"
  - "iojs"
services:
  - mysql
sudo: required
before_script:
  - mysql -e 'create database test_orm;'
  - mysql -e 'use test_orm; create table test(id int not null, name varchar(32) not null);'
after_success:
  - ./node_modules/.bin/isparta cover ./node_modules/.bin/_mocha --include src/*.js --report lcovonly -- test/*.js -r babel/register && cat ./coverage/lcov.info | coveralls && rm -r ./coverage
